export const Colors = {
  primary: '#CC785C',
  primaryLight: '#F5E8E0',
  primaryForeground: '#ffffff',
  background: '#FAF9F5',
  card: '#ffffff',
  border: '#E8E6DC',
  text: '#1F1E1D',
  textMuted: '#6B6862',
  success: '#5C8D5C',
  successLight: '#E8F2E8',
  warning: '#C89B3C',
  warningLight: '#FDF3DC',
  danger: '#C44536',
  dangerLight: '#FDEAE8',
  white: '#ffffff',
  black: '#000000',
};
